#! /usr/bin/env escript
%% -*- mode=erlang-mode -*-
%% Copyright (c) 2008-2012 Robert Virding. All rights reserved.
%%
%% Redistribution and use in source and binary forms, with or without
%% modification, are permitted provided that the following conditions
%% are met:
%%
%% 1. Redistributions of source code must retain the above copyright
%%    notice, this list of conditions and the following disclaimer.
%% 2. Redistributions in binary form must reproduce the above copyright
%%    notice, this list of conditions and the following disclaimer in the
%%    documentation and/or other materials provided with the distribution.
%%
%% THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
%% "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
%% LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
%% FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
%% COPYRIGHT HOLDERS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
%% INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
%% BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
%% LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
%% CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
%% LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
%% ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
%% POSSIBILITY OF SUCH DAMAGE.

main([]) -> usage();
main(Args0) ->
    fix_code_path(),
    %% Set default options as an orddict.
    Opts0 = [{outdir,"."}],
    {Args1,Opts1} = parse_opts(Args0, Opts0),
    %% Remaing args are filenames, add default options.
    lists:map(fun (A) -> lfe_comp:file(A, [verbose,report|Opts1]) end, Args1).

%% Remove "." from code path to make sure we don't get conflicts with
%% newly compiled files.
fix_code_path() ->
    P0 = code:get_path(),
    P1 = lists:delete(".", P0),
    code:set_path(P1).

parse_opts(["-o",Odir|As], Opts) ->
    parse_opts(As, orddict:store(outdir, Odir, Opts));
parse_opts(As, Opts) -> {As,Opts}.

usage() ->
    Usage =
	"Usage:  lfec [options] file ...\n" ++
	"Options:\n" ++
	"-o name        name of output directory\n",
    io:put_chars(Usage).
